export default function Head() {
  return (
    <>
      <meta name="description" content="Generated by create next app" />
      {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
      <link rel="icon" href="/favicon.ico" />

      {/* <link
        rel="stylesheet"
        precedence="default"
        href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css"
      /> */}

      <title>My Page</title>
    </>
  );
}
